export const TAG_COLORS = {
    "Next.js": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-gray-100",
        hoverBorder: "group-hover/card:border-gray-200",
        hoverText: "group-hover/card:text-gray-700",
        activeBg: "bg-black/10",
        activeBorder: "border-black/30",
        activeText: "text-black",
    },

    "Tailwindcss": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-cyan-50",
        hoverBorder: "group-hover/card:border-cyan-200",
        hoverText: "group-hover/card:text-cyan-700",
        activeBg: "bg-cyan-50",
        activeBorder: "border-cyan-200",
        activeText: "text-cyan-700",
    },

    "Prisma": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-emerald-50",
        hoverBorder: "group-hover/card:border-emerald-200",
        hoverText: "group-hover/card:text-emerald-700",
        activeBg: "bg-emerald-50",
        activeBorder: "border-emerald-200",
        activeText: "text-emerald-700",
    },

    "Neon": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-teal-50",
        hoverBorder: "group-hover/card:border-teal-200",
        hoverText: "group-hover/card:text-teal-700",
        activeBg: "bg-teal-50",
        activeBorder: "border-teal-200",
        activeText: "text-teal-700",
    },

    "Postgresql": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-blue-50",
        hoverBorder: "group-hover/card:border-blue-200",
        hoverText: "group-hover/card:text-blue-700",
        activeBg: "bg-blue-50",
        activeBorder: "border-blue-200",
        activeText: "text-blue-700",
    },

    "Vue.js": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-green-50",
        hoverBorder: "group-hover/card:border-green-200",
        hoverText: "group-hover/card:text-green-700",
        activeBg: "bg-green-50",
        activeBorder: "border-green-200",
        activeText: "text-green-700",
    },

    "Vite": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-purple-50",
        hoverBorder: "group-hover/card:border-purple-200",
        hoverText: "group-hover/card:text-purple-700",
        activeBg: "bg-purple-50",
        activeBorder: "border-purple-200",
        activeText: "text-purple-700",
    },

    "Node.js": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-lime-50",
        hoverBorder: "group-hover/card:border-lime-200",
        hoverText: "group-hover/card:text-lime-700",
        activeBg: "bg-lime-50",
        activeBorder: "border-lime-200",
        activeText: "text-lime-700",
    },

    "Express": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-yellow-50",
        hoverBorder: "group-hover/card:border-yellow-300",
        hoverText: "group-hover/card:text-yellow-700",
        activeBg: "bg-yellow-50",
        activeBorder: "border-yellow-300",
        activeText: "text-yellow-700",
    },

    "MySQL": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-orange-50",
        hoverBorder: "group-hover/card:border-orange-200",
        hoverText: "group-hover/card:text-orange-700",
        activeBg: "bg-orange-50",
        activeBorder: "border-orange-200",
        activeText: "text-orange-700",
    },

    "PHP": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-purple-50",
        hoverBorder: "group-hover/card:border-purple-200",
        hoverText: "group-hover/card:text-purple-700",
        activeBg: "bg-purple-50",
        activeBorder: "border-purple-200",
        activeText: "text-purple-700",
    },

    "Laravel": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-red-50",
        hoverBorder: "group-hover/card:border-red-200",
        hoverText: "group-hover/card:text-red-700",
        activeBg: "bg-red-50",
        activeBorder: "border-red-200",
        activeText: "text-red-700",
    },

    "Inertia": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-violet-50",
        hoverBorder: "group-hover/card:border-violet-200",
        hoverText: "group-hover/card:text-violet-700",
        activeBg: "bg-violet-50",
        activeBorder: "border-violet-200",
        activeText: "text-violet-700",
    },

    "React": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-sky-50",
        hoverBorder: "group-hover/card:border-sky-200",
        hoverText: "group-hover/card:text-sky-700",
        activeBg: "bg-sky-50",
        activeBorder: "border-sky-200",
        activeText: "text-sky-700",
    },

    "ASP.NET": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-purple-50",
        hoverBorder: "group-hover/card:border-purple-200",
        hoverText: "group-hover/card:text-purple-700",
        activeBg: "bg-purple-50",
        activeBorder: "border-purple-200",
        activeText: "text-purple-700",
    },

    "C#": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-blue-50",
        hoverBorder: "group-hover/card:border-blue-200",
        hoverText: "group-hover/card:text-blue-700",
        activeBg: "bg-blue-50",
        activeBorder: "border-blue-200",
        activeText: "text-blue-700",
    },

    "Gin": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-blue-50",
        hoverBorder: "group-hover/card:border-blue-200",
        hoverText: "group-hover/card:text-blue-700",
        activeBg: "bg-blue-50",
        activeBorder: "border-blue-200",
        activeText: "text-blue-700",
    },

    "Golang": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-sky-50",
        hoverBorder: "group-hover/card:border-sky-200",
        hoverText: "group-hover/card:text-sky-700",
        activeBg: "bg-sky-50",
        activeBorder: "border-sky-200",
        activeText: "text-sky-700",
    },

    "Svelte": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-orange-50",
        hoverBorder: "group-hover/card:border-orange-200",
        hoverText: "group-hover/card:text-orange-700",
        activeBg: "bg-orange-50",
        activeBorder: "border-orange-200",
        activeText: "text-orange-700",
    },

    "Python": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-yellow-50",
        hoverBorder: "group-hover/card:border-yellow-200",
        hoverText: "group-hover/card:text-yellow-700",
        activeBg: "bg-yellow-50",
        activeBorder: "border-yellow-200",
        activeText: "text-yellow-700",
    },

    "Flask": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-lime-50",
        hoverBorder: "group-hover/card:border-lime-200",
        hoverText: "group-hover/card:text-lime-700",
        activeBg: "bg-lime-50",
        activeBorder: "border-lime-200",
        activeText: "text-lime-700",
    },

    "SQLite": {
        bg: "bg-neutral-100",
        border: "border-neutral-200",
        text: "text-neutral-500",
        hoverBg: "group-hover/card:bg-blue-50",
        hoverBorder: "group-hover/card:border-blue-200",
        hoverText: "group-hover/card:text-blue-700",
        activeBg: "bg-blue-50",
        activeBorder: "border-blue-200",
        activeText: "text-blue-700",
    },
};
